import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { getCurrentUser, can } from '@/lib/rbac'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { RecordEditDialog } from '@/components/data/record-edit-dialog'
import type { Row } from '@/types/database'

export const dynamic = 'force-dynamic'

type Program = Row<'programs'>
type Company = Row<'companies'>
type Quotation = Row<'quotations'>
type PurchaseOrder = Row<'purchase_orders'>
type Invoice = Row<'invoices'>
type Payment = Row<'payments'>
type TrainingSession = Row<'training_sessions'>
type ParticipantRoster = Row<'participant_roster'>

const pipelineOptions = ['LEAD_REGISTERED','PROPOSAL_SUBMITTED','QUOTATION_APPROVED','PO_RECEIVED','INVOICED','PAID','TRAINING_COMPLETED','LOST'].map((value) => ({ value, label: value.replaceAll('_', ' ') }))
const quotationOptions = ['DRAFT','SENT','PENDING','APPROVED','REJECTED','EXPIRED'].map((value) => ({ value, label: value }))
const paymentOptions = ['UNPAID','PARTIAL','PAID','OVERDUE'].map((value) => ({ value, label: value }))
const r2Options = ['UPCOMING','PENDING_DATA','COMPLETED'].map((value) => ({ value, label: value.replaceAll('_', ' ') }))
const participationOptions = ['CERTIFIED','ATTENDED'].map((value) => ({ value, label: value }))
const weekOptions = [{ value: 'week1', label: 'Week 1' }, { value: 'week2', label: 'Week 2' }]
const dateValue = (value: string | null | undefined) => value ? value.slice(0, 10) : ''
const money = (value: number | null | undefined) => `RM ${Number(value ?? 0).toLocaleString('en-MY', { minimumFractionDigits: 2 })}`

export default async function ProgramEditPage({ params }: { params: Promise<{ code: string }> }) {
  const { code } = await params
  const user = await getCurrentUser()
  if (!user) redirect('/login')
  if (!can(user.role, ['super_admin', 'masb_team'])) redirect(`/dashboard/programs/${encodeURIComponent(code)}`)

  const supabase = await createClient()
  const { data: programData } = await supabase.from('programs').select('*').eq('program_code', code).single()
  if (!programData) notFound()
  const program = programData as Program
  const [companyResult, quotationsResult, poResult, invoiceResult, trainingResult] = await Promise.all([
    supabase.from('companies').select('*').order('canonical_name'),
    supabase.from('quotations').select('*').eq('program_id', program.id).order('quotation_date', { ascending: false }),
    supabase.from('purchase_orders').select('*').eq('program_id', program.id).order('po_date', { ascending: false }),
    supabase.from('invoices').select('*').eq('program_id', program.id).order('invoice_date', { ascending: false }),
    supabase.from('training_sessions').select('*').eq('program_id', program.id).order('start_date', { ascending: false }),
  ])
  const companies = (companyResult.data ?? []) as Company[]
  const quotations = (quotationsResult.data ?? []) as Quotation[]
  const purchaseOrders = (poResult.data ?? []) as PurchaseOrder[]
  const invoices = (invoiceResult.data ?? []) as Invoice[]
  const trainingSessions = (trainingResult.data ?? []) as TrainingSession[]
  const invoiceIds = invoices.map((row) => row.id)
  const sessionIds = trainingSessions.map((row) => row.id)
  const [paymentsResult, rosterResult] = await Promise.all([
    invoiceIds.length ? supabase.from('payments').select('*').in('invoice_id', invoiceIds).order('payment_date', { ascending: false }) : Promise.resolve({ data: [], error: null }),
    sessionIds.length ? supabase.from('participant_roster').select('*').in('training_session_id', sessionIds).order('full_name').limit(500) : Promise.resolve({ data: [], error: null }),
  ])
  const payments = (paymentsResult.data ?? []) as Payment[]
  const roster = (rosterResult.data ?? []) as ParticipantRoster[]
  const companyOptions = companies.map((company) => ({ value: company.id, label: company.canonical_name }))

  return <div className="space-y-6 p-6">
    <div className="flex flex-wrap items-start justify-between gap-3">
      <div><Link href={`/dashboard/programs/${encodeURIComponent(code)}`} className="text-xs font-semibold text-blue-600 hover:underline">← Back to Program 360</Link><h1 className="mt-2 text-2xl font-bold tracking-tight">Edit Program Data</h1><p className="mt-1 text-sm text-slate-500">Update operational data and statuses. Changes are subject to your role and Supabase RLS.</p></div>
      <Button asChild variant="outline"><Link href={`/dashboard/programs/${encodeURIComponent(code)}`}>Cancel</Link></Button>
    </div>
    <Card><CardHeader><CardTitle className="text-base">Program</CardTitle></CardHeader><CardContent className="p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">Program Code</p><p className="mt-1 font-semibold text-slate-900">{program.program_code}</p></div><div className="flex items-end justify-end"><RecordEditDialog table="programs" id={program.id} title={program.program_code} values={{ title: program.title, company_id: program.company_id, category: program.category, training_type: program.training_type, current_stage: program.current_stage, client_category: program.client_category, sector: program.sector, lead_date: dateValue(program.lead_date), forecast_value: program.forecast_value, probability: program.probability, needs_review: program.needs_review }} fields={[{ key: 'title', label: 'Program Title', type: 'text' }, { key: 'company_id', label: 'Company', type: 'select', options: companyOptions }, { key: 'category', label: 'Category', type: 'text' }, { key: 'training_type', label: 'Training Type', type: 'text' }, { key: 'current_stage', label: 'Stage / Status', type: 'select', options: pipelineOptions }, { key: 'client_category', label: 'Client Category', type: 'text' }, { key: 'sector', label: 'Sector', type: 'text' }, { key: 'lead_date', label: 'Lead Date', type: 'date' }, { key: 'forecast_value', label: 'Forecast Value', type: 'number', step: '0.01' }, { key: 'probability', label: 'Probability', type: 'number', step: '0.001' }, { key: 'needs_review', label: 'Needs Review', type: 'checkbox' }]} /></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Forecast</p><p className="mt-1 font-semibold tabular-nums">{money(program.forecast_value)}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Weighted</p><p className="mt-1 font-semibold tabular-nums">{money(program.weighted_value)}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Current Stage</p><p className="mt-1 font-semibold">{program.current_stage.replaceAll('_', ' ')}</p></div></div></CardContent></Card>
    <section className="space-y-4"><div><h2 className="text-lg font-semibold">Quotations</h2><p className="text-xs text-slate-500">Edit quotation details and status. Generated audit fields remain read-only.</p></div><div className="grid gap-4 lg:grid-cols-2">{quotations.map((row) => <Card key={row.id}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{row.quotation_no_raw}</p><p className="mt-1 text-xs text-slate-500">{row.quotation_date ?? 'No date'} · {money(row.final_price)}</p></div><RecordEditDialog table="quotations" id={row.id} title={row.quotation_no_raw} values={{ quotation_no_raw: row.quotation_no_raw, quotation_date: dateValue(row.quotation_date), final_price: row.final_price, status: row.status, prepared_by: row.prepared_by }} fields={[{ key: 'quotation_no_raw', label: 'Quotation Number', type: 'text' }, { key: 'quotation_date', label: 'Quotation Date', type: 'date' }, { key: 'final_price', label: 'Final Price', type: 'number', step: '0.01' }, { key: 'status', label: 'Status', type: 'select', options: quotationOptions }, { key: 'prepared_by', label: 'Prepared By', type: 'text' }]} /></div></CardContent></Card>)}</div>{quotations.length === 0 ? <Empty text="No quotations for this program." /> : null}</section>
    <section className="space-y-4"><div><h2 className="text-lg font-semibold">Purchase Orders</h2></div><div className="grid gap-4 lg:grid-cols-2">{purchaseOrders.map((row) => <Card key={row.id}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{row.po_no ?? 'PO without number'}</p><p className="mt-1 text-xs text-slate-500">{row.po_date ?? 'No date'} · {money(row.po_value)}</p></div><RecordEditDialog table="purchase_orders" id={row.id} title={row.po_no ?? 'Purchase Order'} values={{ quotation_id: row.quotation_id, po_no: row.po_no, po_date: dateValue(row.po_date), po_value: row.po_value }} fields={[{ key: 'po_no', label: 'PO Number', type: 'text' }, { key: 'po_date', label: 'PO Date', type: 'date' }, { key: 'po_value', label: 'PO Value', type: 'number', step: '0.01' }]} /></div></CardContent></Card>)}</div>{purchaseOrders.length === 0 ? <Empty text="No purchase orders for this program." /> : null}</section>
    <section className="space-y-4"><div><h2 className="text-lg font-semibold">Invoices &amp; Payments</h2><p className="text-xs text-slate-500">Invoice and payment information can be edited by Super Admin and MASB Team. Generated audit fields remain read-only.</p></div><div className="grid gap-4 lg:grid-cols-2">{invoices.map((row) => <Card key={row.id}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{row.invoice_no}</p><p className="mt-1 text-xs text-slate-500">{row.invoice_date ?? 'No date'} · {money(row.total_value)} · {row.payment_status}</p></div><RecordEditDialog table="invoices" id={row.id} title={row.invoice_no} values={{ invoice_no: row.invoice_no, invoice_date: dateValue(row.invoice_date), invoice_value_excl_sst: row.invoice_value_excl_sst, sst_amount: row.sst_amount, payment_terms_days: row.payment_terms_days, payment_status: row.payment_status, pic: row.pic }} fields={[{ key: 'invoice_no', label: 'Invoice Number', type: 'text' }, { key: 'invoice_date', label: 'Invoice Date', type: 'date' }, { key: 'invoice_value_excl_sst', label: 'Invoice Value Excl. SST', type: 'number', step: '0.01' }, { key: 'sst_amount', label: 'SST Amount', type: 'number', step: '0.01' }, { key: 'payment_terms_days', label: 'Payment Terms (Days)', type: 'number', step: '1' }, { key: 'payment_status', label: 'Payment Status', type: 'select', options: paymentOptions }, { key: 'pic', label: 'PIC', type: 'text' }]} /></div><div className="mt-3 border-t border-slate-100 pt-3">{payments.filter((payment) => payment.invoice_id === row.id).map((payment) => <div key={payment.id} className="flex items-center justify-between gap-3 py-2 text-xs"><span className="tabular-nums">{money(payment.amount)} · {payment.payment_date}</span><RecordEditDialog table="payments" id={payment.id} title={`Payment for ${row.invoice_no}`} values={{ amount: payment.amount, payment_date: dateValue(payment.payment_date), method: payment.method, reference_no: payment.reference_no }} fields={[{ key: 'amount', label: 'Amount', type: 'number', step: '0.01' }, { key: 'payment_date', label: 'Payment Date', type: 'date' }, { key: 'method', label: 'Method', type: 'text' }, { key: 'reference_no', label: 'Reference Number', type: 'text' }]} /></div>)}{payments.filter((payment) => payment.invoice_id === row.id).length === 0 ? <p className="text-xs text-slate-400">No payments recorded.</p> : null}</div></CardContent></Card>)}</div>{invoices.length === 0 ? <Empty text="No invoices for this program." /> : null}</section>
    <section className="space-y-4"><div><h2 className="text-lg font-semibold">R2 Training Sessions</h2></div><div className="grid gap-4 lg:grid-cols-2">{trainingSessions.map((row) => <Card key={row.id}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{row.session_title}</p><p className="mt-1 text-xs text-slate-500">{row.start_date ?? 'No start date'} · {row.r2_status.replaceAll('_', ' ')}</p></div><RecordEditDialog table="training_sessions" id={row.id} title={row.session_title} values={{ session_title: row.session_title, session_type: row.session_type, start_date: dateValue(row.start_date), end_date: dateValue(row.end_date), venue: row.venue, duration_days: row.duration_days, r2_status: row.r2_status }} fields={[{ key: 'session_title', label: 'Session Title', type: 'text' }, { key: 'session_type', label: 'Session Type', type: 'text' }, { key: 'start_date', label: 'Start Date', type: 'date' }, { key: 'end_date', label: 'End Date', type: 'date' }, { key: 'venue', label: 'Venue', type: 'text' }, { key: 'duration_days', label: 'Duration (Days)', type: 'number', step: '0.01' }, { key: 'r2_status', label: 'R2 Status', type: 'select', options: r2Options }]} /></div></CardContent></Card>)}</div>{trainingSessions.length === 0 ? <Empty text="No training sessions for this program." /> : null}</section>
    <section className="space-y-4"><div><h2 className="text-lg font-semibold">Participant Roster</h2><p className="text-xs text-slate-500">Up to 500 participants are shown. Use Edit to correct participant details or attendance date.</p></div><div className="overflow-x-auto rounded-lg border border-slate-200"><table className="w-full min-w-[850px] text-[13px] leading-[1.4]"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="p-3 text-left">Name</th><th className="p-3 text-left">Certificate</th><th className="p-3 text-left">Type</th><th className="p-3 text-left">Week</th><th className="p-3 text-left">Bumiputera</th><th className="p-3 text-left">Attendance Date</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{roster.map((row) => <tr key={row.id} className="border-t border-slate-100 odd:bg-white even:bg-slate-50/50"><td className="p-3 font-medium">{row.full_name}</td><td className="p-3">{row.cert_no ?? '—'}</td><td className="p-3">{row.participation_type}</td><td className="p-3">{row.week_label ? weekOptions.find((option) => option.value === row.week_label)?.label ?? row.week_label : '—'}</td><td className="p-3">{row.is_bumiputera ? 'Yes' : 'No'}</td><td className="p-3">{row.attendance_date ?? '—'}</td><td className="p-3 text-right"><RecordEditDialog table="participant_roster" id={row.id} title={row.full_name} values={{ full_name: row.full_name, cert_no: row.cert_no, participation_type: row.participation_type, week_label: row.week_label, is_bumiputera: row.is_bumiputera, attendance_date: dateValue(row.attendance_date) }} fields={[{ key: 'full_name', label: 'Full Name', type: 'text', required: true }, { key: 'cert_no', label: 'Certificate Number', type: 'text' }, { key: 'participation_type', label: 'Participation Type', type: 'select', options: participationOptions }, { key: 'week_label', label: 'Week', type: 'select', options: weekOptions }, { key: 'is_bumiputera', label: 'Bumiputera', type: 'checkbox' }, { key: 'attendance_date', label: 'Attendance Date', type: 'date' }]} /></td></tr>)}</tbody></table></div>{roster.length === 0 ? <Empty text="No participants for this program." /> : null}</section>
  </div>
}

function Empty({ text }: { text: string }) { return <div className="rounded-lg border border-dashed border-slate-200 p-6 text-center text-sm text-slate-400">{text}</div> }
