'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { CheckCircle2, ExternalLink, Search } from 'lucide-react'
import type { Database } from '@/types/database'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { StatusBadge } from '@/components/ui/status-badge'

type ActionRow = Database['public']['Views']['vw_action_required']['Row']
type ActionCenterTableProps = { rows: ActionRow[] }
function priorityStatus(priority: string | null) { switch (priority?.toUpperCase()) { case 'HIGH': return 'OVERDUE' as const; case 'MEDIUM': return 'PENDING' as const; default: return 'COMPLETED' as const } }
function categoryClass(category: string | null) { switch (category?.toUpperCase()) { case 'OVERDUE_INVOICE': case 'OVERDUE': return 'border-red-200 bg-red-50 text-red-700'; case 'PENDING_QUOTATION': return 'border-amber-200 bg-amber-50 text-amber-700'; case 'PAYMENT': return 'border-blue-200 bg-blue-50 text-blue-700'; case 'MISSING_R2': return 'border-amber-200 bg-amber-50 text-amber-700'; default: return 'border-slate-200 bg-slate-50 text-slate-700' } }
export function ActionCenterTable({ rows }: ActionCenterTableProps) {
  const [search, setSearch] = useState(''); const [priority, setPriority] = useState('ALL'); const [category, setCategory] = useState('ALL'); const [followedUp, setFollowedUp] = useState<Set<string>>(new Set())
  const categories = useMemo(() => ['ALL', ...Array.from(new Set(rows.map(r => r.category?.toUpperCase()).filter(Boolean) as string[]))], [rows])
  const filteredRows = useMemo(() => rows.filter(row => { const needle = search.trim().toLowerCase(); return (!needle || [row.company_name, row.program_code, row.category].some(v => v?.toLowerCase().includes(needle))) && (priority === 'ALL' || row.priority?.toUpperCase() === priority) && (category === 'ALL' || row.category?.toUpperCase() === category) }), [rows, search, priority, category])
  function markFollowedUp(key: string) { setFollowedUp(current => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next }) }
  const critical = rows.filter(r => r.priority?.toUpperCase() === 'HIGH').length; const overdueAmount = rows.reduce((sum, r) => sum + (['OVERDUE','OVERDUE_INVOICE'].includes(r.category?.toUpperCase() ?? '') ? Number(r.amount ?? 0) : 0), 0)
  return <Card><CardContent className="p-4 sm:p-6">
    <div className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3"><p className="text-sm font-bold text-red-800">{critical} Critical Action Items</p><p className="mt-0.5 text-xs text-red-700">Jumlah risiko overdue: RM {overdueAmount.toLocaleString('en-MY', { minimumFractionDigits: 2 })}</p></div>
    <div className="mb-4 flex flex-col gap-3"><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Cari syarikat, program atau kategori" className="pl-9" /></div><div className="flex gap-1 overflow-x-auto pb-1">{['ALL','HIGH','MEDIUM','LOW'].map(v => <Button key={v} type="button" size="sm" variant={priority === v ? 'default' : 'outline'} onClick={() => setPriority(v)} className="shrink-0 text-xs">{v === 'ALL' ? 'ALL' : v}</Button>)}<span className="mx-1 border-l border-slate-200" />{categories.map(v => <Button key={v} type="button" size="sm" variant={category === v ? 'default' : 'outline'} onClick={() => setCategory(v)} className="shrink-0 text-xs">{v === 'ALL' ? 'ALL' : v.replaceAll('_',' ')}</Button>)}</div></div>
    <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[980px] text-[13px] leading-[1.4]"><thead className="sticky top-0 z-10 bg-slate-50 text-[11px] font-semibold uppercase tracking-wide text-slate-500"><tr><th className="p-3 text-left">Priority</th><th className="p-3 text-left">Category</th><th className="p-3 text-left">Title / Client</th><th className="p-3 text-left">PIC</th><th className="p-3 text-right">Amount</th><th className="p-3 text-right">Days</th><th className="p-3 text-left">Action</th></tr></thead><tbody>{filteredRows.map(row => { const key = row.record_id ?? `${row.category}-${row.program_code ?? row.company_name ?? 'action'}`; const done = followedUp.has(key); return <tr key={key} className="border-t border-slate-100 odd:bg-white even:bg-slate-50/50 hover:bg-slate-100/70"><td className="p-3"><StatusBadge status={priorityStatus(row.priority)} label={row.priority ?? 'LOW'} /></td><td className="p-3"><Badge className={categoryClass(row.category)}>{row.category ?? 'ACTION'}</Badge></td><td className="p-3"><p className="font-semibold text-slate-900">{row.company_name ?? '—'}</p><p className="text-xs text-slate-500">{row.program_code ?? '—'}</p></td><td className="p-3 text-slate-600">PIC</td><td className="p-3 text-right font-medium tabular-nums">{row.amount == null ? '—' : `RM ${Number(row.amount).toLocaleString('en-MY', { minimumFractionDigits: 2 })}`}</td><td className="p-3 text-right tabular-nums">{row.days_outstanding ?? '—'}</td><td className="p-3"><div className="flex gap-2">{row.program_code && <Button asChild size="sm" variant="outline" className="h-8 text-xs"><Link href={`/dashboard/programs/${encodeURIComponent(row.program_code)}`}><ExternalLink className="mr-1 h-3.5 w-3.5" />Buka</Link></Button>}<Button size="sm" variant={done ? 'secondary' : 'outline'} className="h-8 text-xs" onClick={() => markFollowedUp(key)}><CheckCircle2 className="mr-1 h-3.5 w-3.5" />{done ? 'Selesai' : 'Tindak'}</Button></div></td></tr> })}</tbody></table></div>
    {filteredRows.length === 0 && <div className="py-10 text-center text-sm text-slate-500">Tiada item sepadan dengan penapis semasa.</div>}{filteredRows.length > 0 && <p className="mt-3 text-xs text-slate-500">Menunjukkan {filteredRows.length} daripada {rows.length} item tindakan.</p>}
  </CardContent></Card>
}
