import { BellRing, BriefcaseBusiness, CircleDollarSign, GraduationCap, Target, TrendingUp } from 'lucide-react'
import { KpiHeroCard } from '@/components/dashboard/kpi-hero-card'
import { R3FunnelInteractive, type R3FunnelData } from './r3-funnel-interactive'
import { R1ReconciliationInteractive, type R1ReconciliationData } from './r1-reconciliation-interactive'
import { R2DemographicsInteractive, type R2DemographicsData } from './r2-demographics-interactive'
import { Separator } from '@/components/ui/separator'

type R1 = R1ReconciliationData & { count:number }
type R2 = R2DemographicsData & { count:number }
type Props = { r3:R3FunnelData; r1:R1; r2:R2; actions:{priority:string|null;category:string|null;company_name:string|null;program_code:string|null;days_outstanding:number|null}[] }

export function ExecutiveBentoDashboard({r3,r1,r2,actions}:Props){ const alerts=actions.filter(a=>a.priority?.toUpperCase()==='HIGH').length; return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Executive command centre</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Performance Overview</h1><p className="mt-1 text-sm text-slate-500">R1 kewangan · R2 training · R3 sales pipeline</p></div><select aria-label="Quarter selector" className="h-10 rounded-lg border bg-white px-3 text-sm font-medium shadow-sm"><option>Q3 2026</option><option>Q2 2026</option><option>Q1 2026</option><option>Q4 2025</option></select></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiHeroCard label="R3 Pipeline" value={`RM ${r3.forecast.toLocaleString('en-MY')}`} icon={BriefcaseBusiness} variant="blue" progress={r3.forecast?Math.min(100,r3.secured/r3.forecast*100):0}/><KpiHeroCard label="R3 Weighted" value={`RM ${r3.weighted.toLocaleString('en-MY')}`} icon={Target} variant="indigo"/><KpiHeroCard label="R1 Collected" value={`RM ${r1.collected.toLocaleString('en-MY')}`} icon={CircleDollarSign} variant="emerald" progress={r1.collectionRate}/><KpiHeroCard label="R1 Net Profit" value={`RM ${r1.profit.toLocaleString('en-MY')}`} icon={TrendingUp} variant="violet"/></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiHeroCard label="Outstanding" value={`RM ${r1.outstanding.toLocaleString('en-MY')}`} icon={CircleDollarSign} variant="rose"/><KpiHeroCard label="Training Sessions" value={r2.sessions} icon={GraduationCap} variant="cyan"/><KpiHeroCard label="Participants" value={r2.participants.toLocaleString('en-MY')} icon={GraduationCap} variant="amber"/><KpiHeroCard label="High Priority" value={alerts} icon={BellRing} variant="slate" href="/dashboard/action-center"/></div><Separator/><div className="grid gap-4 xl:grid-cols-2"><R3FunnelInteractive data={r3}/><R1ReconciliationInteractive data={r1}/></div><R2DemographicsInteractive data={r2}/><div className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Executive Action Radar</h2><p className="text-sm text-slate-500">Tindakan berkeutamaan tinggi daripada Supabase.</p></div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700">{alerts} high</span></div><div className="mt-4 grid gap-2 md:grid-cols-3">{actions.slice(0,6).map((a,i)=><div key={`${a.program_code}-${i}`} className="rounded-lg border p-3"><p className="text-xs font-semibold text-slate-500">{a.category ?? 'ACTION'}</p><p className="mt-1 truncate text-sm font-medium">{a.company_name ?? 'Unknown company'}</p><p className="mt-1 text-xs text-slate-400">{a.days_outstanding ?? 0} days outstanding</p></div>)}</div></div></div> }
