export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[]
export type UserRole='super_admin'|'admin'|'manager'|'pic'|'viewer'
export type PipelineStage='LEAD_REGISTERED'|'PROPOSAL_SUBMITTED'|'QUOTATION_APPROVED'|'PO_RECEIVED'|'INVOICED'|'PAID'|'TRAINING_COMPLETED'|'LOST'
export type QuotationStatus='DRAFT'|'SENT'|'PENDING'|'APPROVED'|'REJECTED'|'EXPIRED'
export type PaymentStatus='UNPAID'|'PARTIAL'|'PAID'|'OVERDUE'
export type R2Status='COMPLETED'|'PENDING_DATA'|'UPCOMING'
export type Row<T extends keyof Database['public']['Tables']>=Database['public']['Tables'][T]['Row']
export type Insert<T extends keyof Database['public']['Tables']>=Database['public']['Tables'][T]['Insert']
export type Update<T extends keyof Database['public']['Tables']>=Database['public']['Tables'][T]['Update']
export interface Database{__InternalSupabase:{PostgrestVersion:'14.17'};public:{Tables:{
profiles:{Row:{id:string;full_name:string;email:string;role:UserRole;is_active:boolean;must_reset_password:boolean;created_at:string;updated_at:string};Insert:{id:string;full_name:string;email:string;role?:UserRole;is_active?:boolean;must_reset_password?:boolean;created_at?:string;updated_at?:string};Update:{id?:string;full_name?:string;email?:string;role?:UserRole;is_active?:boolean;must_reset_password?:boolean;created_at?:string;updated_at?:string};Relationships:[]}
companies:{Row:{id:string;canonical_name:string;aliases:string[];client_category:string|null;sector:string|null;is_merged_into:string|null;created_at:string;updated_at:string};Insert:{id?:string;canonical_name:string;aliases?:string[];client_category?:string|null;sector?:string|null;is_merged_into?:string|null;created_at?:string;updated_at?:string};Update:{id?:string;canonical_name?:string;aliases?:string[];client_category?:string|null;sector?:string|null;is_merged_into?:string|null;created_at?:string;updated_at?:string};Relationships:[]}
programs:{Row:{id:string;program_code:string;title:string;company_id:string;category:string|null;training_type:string|null;current_stage:PipelineStage;client_category:string|null;sector:string|null;pic_user_id:string|null;account_manager_user_id:string|null;lead_date:string|null;forecast_value:number|null;probability:number|null;weighted_value:number|null;needs_review:boolean;created_at:string;updated_at:string};Insert:{id?:string;program_code:string;title:string;company_id:string;category?:string|null;training_type?:string|null;current_stage?:PipelineStage;client_category?:string|null;sector?:string|null;pic_user_id?:string|null;account_manager_user_id?:string|null;lead_date?:string|null;forecast_value?:number|null;probability?:number|null;weighted_value?:number|null;needs_review?:boolean;created_at?:string;updated_at?:string};Update:{id?:string;program_code?:string;title?:string;company_id?:string;category?:string|null;training_type?:string|null;current_stage?:PipelineStage;client_category?:string|null;sector?:string|null;pic_user_id?:string|null;account_manager_user_id?:string|null;lead_date?:string|null;forecast_value?:number|null;probability?:number|null;weighted_value?:number|null;needs_review?:boolean;created_at?:string;updated_at?:string};Relationships:[]}
pipeline_stage_history:{Row:{id:string;program_id:string;stage:PipelineStage;changed_at:string;changed_by:string|null;note:string|null;is_override:boolean;override_reason:string|null;source_system:string|null};Insert:{id?:string;program_id:string;stage:PipelineStage;changed_at?:string;changed_by?:string|null;note?:string|null;is_override?:boolean;override_reason?:string|null;source_system?:string|null};Update:{id?:string;program_id?:string;stage?:PipelineStage;changed_at?:string;changed_by?:string|null;note?:string|null;is_override?:boolean;override_reason?:string|null;source_system?:string|null};Relationships:[]}
quotations:{Row:{id:string;program_id:string;quotation_no_raw:string;quotation_date:string|null;final_price:number|null;status:QuotationStatus;prepared_by:string|null;created_at:string;updated_at:string};Insert:{id?:string;program_id:string;quotation_no_raw:string;quotation_date?:string|null;final_price?:number|null;status?:QuotationStatus;prepared_by?:string|null;created_at?:string;updated_at?:string};Update:{id?:string;program_id?:string;quotation_no_raw?:string;quotation_date?:string|null;final_price?:number|null;status?:QuotationStatus;prepared_by?:string|null;created_at?:string;updated_at?:string};Relationships:[]}
purchase_orders:{Row:{id:string;program_id:string;quotation_id:string|null;po_no:string|null;po_date:string|null;po_value:number|null;created_at:string};Insert:{id?:string;program_id:string;quotation_id?:string|null;po_no?:string|null;po_date?:string|null;po_value?:number|null;created_at?:string};Update:{id?:string;program_id?:string;quotation_id?:string|null;po_no?:string|null;po_date?:string|null;po_value?:number|null;created_at?:string};Relationships:[]}
invoices:{Row:{id:string;program_id:string;quotation_id:string|null;po_id:string|null;invoice_no:string;invoice_date:string|null;invoice_value_excl_sst:number;sst_amount:number;total_value:number|null;payment_terms_days:number;due_date:string|null;payment_status:PaymentStatus;pic:string|null;created_at:string;updated_at:string};Insert:{id?:string;program_id:string;quotation_id?:string|null;po_id?:string|null;invoice_no:string;invoice_date?:string|null;invoice_value_excl_sst?:number;sst_amount?:number;payment_terms_days?:number;payment_status?:PaymentStatus;pic?:string|null;created_at?:string;updated_at?:string};Update:{id?:string;program_id?:string;quotation_id?:string|null;po_id?:string|null;invoice_no?:string;invoice_date?:string|null;invoice_value_excl_sst?:number;sst_amount?:number;payment_terms_days?:number;payment_status?:PaymentStatus;pic?:string|null;created_at?:string;updated_at?:string};Relationships:[]}
payments:{Row:{id:string;invoice_id:string;amount:number;payment_date:string;method:string|null;reference_no:string|null;recorded_by:string|null;created_at:string};Insert:{id?:string;invoice_id:string;amount:number;payment_date?:string;method?:string|null;reference_no?:string|null;recorded_by?:string|null;created_at?:string};Update:{id?:string;invoice_id?:string;amount?:number;payment_date?:string;method?:string|null;reference_no?:string|null;recorded_by?:string|null;created_at?:string};Relationships:[]}
training_sessions:{Row:{id:string;program_id:string;session_title:string;session_type:string|null;start_date:string|null;end_date:string|null;venue:string|null;duration_days:number|null;r2_status:R2Status;created_at:string};Insert:{id?:string;program_id:string;session_title:string;session_type?:string|null;start_date?:string|null;end_date?:string|null;venue?:string|null;duration_days?:number|null;r2_status?:R2Status;created_at?:string};Update:{id?:string;program_id?:string;session_title?:string;session_type?:string|null;start_date?:string|null;end_date?:string|null;venue?:string|null;duration_days?:number|null;r2_status?:R2Status;created_at?:string};Relationships:[]}
data_quality_exceptions:{Row:{id:string;type:string;severity:string;description:string;related_table:string|null;related_id:string|null;status:string;resolved_by:string|null;resolved_at:string|null;resolution_note:string|null;created_at:string};Insert:{id?:string;type:string;severity?:string;description:string;related_table?:string|null;related_id?:string|null;status?:string;resolved_by?:string|null;resolved_at?:string|null;resolution_note?:string|null;created_at?:string};Update:{id?:string;type?:string;severity?:string;description?:string;related_table?:string|null;related_id?:string|null;status?:string;resolved_by?:string|null;resolved_at?:string|null;resolution_note?:string|null;created_at?:string};Relationships:[]}
audit_log:{Row:{id:string;table_name:string;record_id:string;action:string;old_value:Json|null;new_value:Json|null;changed_by:string|null;changed_at:string;source:string};Insert:{id?:string;table_name:string;record_id:string;action:string;old_value?:Json|null;new_value?:Json|null;changed_by?:string|null;changed_at?:string;source?:string};Update:{id?:string;table_name?:string;record_id?:string;action?:string;old_value?:Json|null;new_value?:Json|null;changed_by?:string|null;changed_at?:string;source?:string};Relationships:[]}
};Views:{vw_action_required:{Row:{category:string|null;record_id:string|null;program_code:string|null;company_name:string|null;amount:number|null;days_outstanding:number|null;pic:string|null;priority:string|null};Relationships:[]};vw_r3_sales_funnel:{Row:{program_code:string|null;company_name:string|null;title:string|null;current_stage:PipelineStage|null;forecast_value:number|null;probability:number|null;weighted_value:number|null;pic_user_id:string|null;sector:string|null;lead_date:string|null;secured_value:number|null};Relationships:[]}};Functions:{};Enums:{payment_status:PaymentStatus;pipeline_stage:PipelineStage;quotation_status:QuotationStatus;r2_status:R2Status;user_role:UserRole};CompositeTypes:{}}}
export type Tables<T extends keyof (Database['public']['Tables']&Database['public']['Views'])>= (Database['public']['Tables']&Database['public']['Views'])[T] extends {Row:infer R}?R:never
export type TablesInsert<T extends keyof Database['public']['Tables']>=Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']>=Database['public']['Tables'][T]['Update']
export type Enums<T extends keyof Database['public']['Enums']>=Database['public']['Enums'][T]
