export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type UserRole = 'super_admin' | 'admin' | 'manager' | 'pic' | 'viewer'
export type PipelineStage = 'LEAD_REGISTERED' | 'PROPOSAL_SUBMITTED' | 'QUOTATION_APPROVED' | 'PO_RECEIVED' | 'INVOICED' | 'PAID' | 'TRAINING_COMPLETED' | 'LOST'
export type QuotationStatus = 'DRAFT' | 'SENT' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'EXPIRED'
export type PaymentStatus = 'UNPAID' | 'PARTIAL' | 'PAID' | 'OVERDUE'
export type R2Status = 'COMPLETED' | 'PENDING_DATA' | 'UPCOMING'
export type ParticipantCategory = 'WAFER_FAB' | 'FA_MA' | 'AI' | 'OTHERS'
export type ImportBatchStatus = 'UPLOADED' | 'PARSING' | 'STAGED' | 'VALIDATING' | 'MATCHING' | 'READY' | 'COMMITTING' | 'COMPLETED' | 'PARSING_FAILED' | 'VALIDATION_FAILED' | 'MATCHING_FAILED' | 'ROLLED_BACK' | 'CANCELLED' | 'FAILED'
export type ImportValidationStatus = 'PENDING' | 'VALID' | 'WARNING' | 'ERROR'
export type ImportMatchingStatus = 'PENDING' | 'EXACT' | 'ALIAS' | 'COMPOSITE' | 'FUZZY_REVIEW' | 'AMBIGUOUS' | 'NONE'

export type Row<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Insert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type Update<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

type Table<RowT, InsertT = RowT, UpdateT = Partial<InsertT>> = { Row: RowT; Insert: InsertT; Update: UpdateT; Relationships: [] }
type View<RowT> = { Row: RowT; Relationships: [] }

export interface Database {
  __InternalSupabase: { PostgrestVersion: '15.0.0' }
  public: {
    Tables: {
      profiles: Table<{ id: string; full_name: string; email: string; role: UserRole; is_active: boolean; must_reset_password: boolean; created_at: string; updated_at: string }, { id: string; full_name: string; email: string; role?: UserRole; is_active?: boolean; must_reset_password?: boolean; created_at?: string; updated_at?: string }>
      companies: Table<{ id: string; canonical_name: string; aliases: string[]; client_category: string | null; sector: string | null; is_merged_into: string | null; created_at: string; updated_at: string }, { id?: string; canonical_name: string; aliases?: string[]; client_category?: string | null; sector?: string | null; is_merged_into?: string | null; created_at?: string; updated_at?: string }>
      contacts: Table<{ id: string; company_id: string; full_name: string; designation: string | null; email: string | null; phone: string | null; created_at: string }, { id?: string; company_id: string; full_name: string; designation?: string | null; email?: string | null; phone?: string | null; created_at?: string }>
      status_dictionary: Table<{ id: string; source_system: string; entity_type: string; raw_value: string; canonical_value: string; created_at: string }, { id?: string; source_system: string; entity_type: string; raw_value: string; canonical_value: string; created_at?: string }>
      company_alias_map: Table<{ id: string; alias_text: string; company_id: string; created_at: string }, { id?: string; alias_text: string; company_id: string; created_at?: string }>
      programs: Table<{ id: string; program_code: string; title: string; company_id: string; category: string | null; training_type: string | null; current_stage: PipelineStage; client_category: string | null; sector: string | null; pic_user_id: string | null; account_manager_user_id: string | null; lead_date: string | null; forecast_value: number | null; probability: number | null; weighted_value: number | null; needs_review: boolean; source_file: string | null; source_sheet: string | null; source_row: number | null; row_hash: string | null; created_at: string; updated_at: string }, { id?: string; program_code: string; title: string; company_id: string; category?: string | null; training_type?: string | null; current_stage?: PipelineStage; client_category?: string | null; sector?: string | null; pic_user_id?: string | null; account_manager_user_id?: string | null; lead_date?: string | null; forecast_value?: number | null; probability?: number | null; weighted_value?: number | null; needs_review?: boolean; source_file?: string | null; source_sheet?: string | null; source_row?: number | null; row_hash?: string | null; created_at?: string; updated_at?: string }>
      pipeline_stage_history: Table<{ id: string; program_id: string; stage: PipelineStage; changed_at: string; changed_by: string | null; note: string | null; is_override: boolean; override_reason: string | null; source_system: string | null }, { id?: string; program_id: string; stage: PipelineStage; changed_at?: string; changed_by?: string | null; note?: string | null; is_override?: boolean; override_reason?: string | null; source_system?: string | null }>
      quotations: Table<{ id: string; program_id: string; quotation_no_raw: string; quotation_date: string | null; final_price: number | null; status: QuotationStatus; prepared_by: string | null; created_at: string; updated_at: string }, { id?: string; program_id: string; quotation_no_raw: string; quotation_date?: string | null; final_price?: number | null; status?: QuotationStatus; prepared_by?: string | null; created_at?: string; updated_at?: string }>
      purchase_orders: Table<{ id: string; program_id: string; quotation_id: string | null; po_no: string | null; po_date: string | null; po_value: number | null; created_at: string }, { id?: string; program_id: string; quotation_id?: string | null; po_no?: string | null; po_date?: string | null; po_value?: number | null; created_at?: string }>
      invoices: Table<{ id: string; program_id: string; quotation_id: string | null; po_id: string | null; invoice_no: string; invoice_date: string | null; invoice_value_excl_sst: number; sst_amount: number; total_value: number | null; payment_terms_days: number; due_date: string | null; payment_status: PaymentStatus; pic: string | null; created_at: string; updated_at: string }, { id?: string; program_id: string; quotation_id?: string | null; po_id?: string | null; invoice_no: string; invoice_date?: string | null; invoice_value_excl_sst?: number; sst_amount?: number; payment_terms_days?: number; payment_status?: PaymentStatus; pic?: string | null; created_at?: string; updated_at?: string }>
      payments: Table<{ id: string; invoice_id: string; amount: number; payment_date: string; method: string | null; reference_no: string | null; recorded_by: string | null; created_at: string }, { id?: string; invoice_id: string; amount: number; payment_date?: string; method?: string | null; reference_no?: string | null; recorded_by?: string | null; created_at?: string }>
      cost_of_sales: Table<{ id: string; invoice_id: string; invoice_no: string | null; invoice_value: number | null; collection: number | null; cost_of_sales_amount: number; mimos_academy_cost: number; commission: number; bro_incentive: number; net_profit: number | null; profit_percentage: number | null; had_formula_error: boolean; source_file: string | null; source_sheet: string | null; source_row: number | null; row_hash: string | null; created_at: string }, { id?: string; invoice_id: string; invoice_no?: string | null; invoice_value?: number | null; collection?: number | null; cost_of_sales_amount?: number; mimos_academy_cost?: number; commission?: number; bro_incentive?: number; net_profit?: number | null; profit_percentage?: number | null; had_formula_error?: boolean; source_file?: string | null; source_sheet?: string | null; source_row?: number | null; row_hash?: string | null; created_at?: string }>
      training_sessions: Table<{ id: string; program_id: string; session_title: string; session_type: string | null; start_date: string | null; end_date: string | null; venue: string | null; duration_days: number | null; r2_status: R2Status; created_at: string }, { id?: string; program_id: string; session_title: string; session_type?: string | null; start_date?: string | null; end_date?: string | null; venue?: string | null; duration_days?: number | null; r2_status?: R2Status; created_at?: string }>
      participant_counts: Table<{ id: string; training_session_id: string; category: string; bumiputera_count: number; non_bumiputera_count: number; total_count: number; source_file: string | null; source_sheet: string | null; source_row: number | null; row_hash: string | null; created_at: string }, { id?: string; training_session_id: string; category?: string; bumiputera_count?: number; non_bumiputera_count?: number; total_count?: number; source_file?: string | null; source_sheet?: string | null; source_row?: number | null; row_hash?: string | null; created_at?: string }>
      participant_roster: Table<{ id: string; training_session_id: string; full_name: string; cert_no: string | null; is_bumiputera: boolean | null; source_file: string | null; source_sheet: string | null; source_row: number | null; row_hash: string | null; created_at: string }, { id?: string; training_session_id: string; full_name: string; cert_no?: string | null; is_bumiputera?: boolean | null; source_file?: string | null; source_sheet?: string | null; source_row?: number | null; row_hash?: string | null; created_at?: string }>
      data_quality_exceptions: Table<{ id: string; type: string; severity: string; description: string; related_table: string | null; related_id: string | null; status: string; resolved_by: string | null; resolved_at: string | null; resolution_note: string | null; created_at: string }, { id?: string; type: string; severity?: string; description: string; related_table?: string | null; related_id?: string | null; status?: string; resolved_by?: string | null; resolved_at?: string | null; resolution_note?: string | null; created_at?: string }>
      audit_log: Table<{ id: string; table_name: string; record_id: string; action: string; old_value: Json | null; new_value: Json | null; changed_by: string | null; changed_at: string; source: string }, { id?: string; table_name: string; record_id: string; action: string; old_value?: Json | null; new_value?: Json | null; changed_by?: string | null; changed_at?: string; source?: string }>
      import_batches: Table<{ id: string; source_type: string; file_name: string; file_size_bytes: number | null; content_type: string | null; status: ImportBatchStatus; created_by: string; total_rows: number; staged_rows: number; valid_rows: number; warning_rows: number; error_rows: number; imported_rows: number; updated_rows: number; skipped_rows: number; exception_rows: number; error_message: string | null; metadata: Json; created_at: string; started_at: string | null; completed_at: string | null }, { id?: string; source_type: string; file_name: string; file_size_bytes?: number | null; content_type?: string | null; status?: ImportBatchStatus; created_by: string; total_rows?: number; staged_rows?: number; valid_rows?: number; warning_rows?: number; error_rows?: number; imported_rows?: number; updated_rows?: number; skipped_rows?: number; exception_rows?: number; error_message?: string | null; metadata?: Json; created_at?: string; started_at?: string | null; completed_at?: string | null }>
      import_staging: Table<{ id: string; batch_id: string; source_type: string; source_row_number: number; raw_data: Json; normalized_data: Json; row_hash: string; validation_status: ImportValidationStatus; matching_status: ImportMatchingStatus; matching_confidence: number | null; matching_rule: string | null; target_table: string | null; target_record_id: string | null; error_message: string | null; warning_message: string | null; metadata: Json; created_at: string; updated_at: string }, { id?: string; batch_id: string; source_type: string; source_row_number: number; raw_data?: Json; normalized_data?: Json; row_hash: string; validation_status?: ImportValidationStatus; matching_status?: ImportMatchingStatus; matching_confidence?: number | null; matching_rule?: string | null; target_table?: string | null; target_record_id?: string | null; error_message?: string | null; warning_message?: string | null; metadata?: Json; created_at?: string; updated_at?: string }>
      import_commit_log: Table<{ id: string; batch_id: string; staging_id: string; target_table: string; target_record_id: string; action: string; committed_at: string; rolled_back_at: string | null; metadata: Json }, { id?: string; batch_id: string; staging_id: string; target_table: string; target_record_id: string; action: string; committed_at?: string; rolled_back_at?: string | null; metadata?: Json }>
    }
    Views: {
      vw_action_required: View<{ category: string | null; record_id: string | null; program_code: string | null; company_name: string | null; amount: number | null; days_outstanding: number | null; pic: string | null; priority: string | null }>
      vw_r1_income_statement: View<{ program_code: string | null; company_name: string | null; title: string | null; invoice_no: string | null; invoice_date: string | null; total_value: number | null; payment_status: PaymentStatus | null; due_date: string | null; days_outstanding: number | null; pic: string | null; cost_of_sales_amount: number | null; net_profit: number | null; profit_pct: number | null }>
      vw_r2_overall_report: View<{ program_code: string | null; session_title: string | null; company_name: string | null; session_type: string | null; start_date: string | null; end_date: string | null; r2_status: R2Status | null; category: string | null; bumiputera_count: number | null; non_bumiputera_count: number | null; total_count: number | null }>
      vw_r3_sales_funnel: View<{ program_code: string | null; company_name: string | null; title: string | null; current_stage: PipelineStage | null; forecast_value: number | null; probability: number | null; weighted_value: number | null; pic_user_id: string | null; sector: string | null; lead_date: string | null; secured_value: number | null }>
    }
    Functions: {}
    Enums: { UserRole: UserRole; PipelineStage: PipelineStage; QuotationStatus: QuotationStatus; PaymentStatus: PaymentStatus; R2Status: R2Status; ParticipantCategory: ParticipantCategory; ImportBatchStatus: ImportBatchStatus; ImportValidationStatus: ImportValidationStatus; ImportMatchingStatus: ImportMatchingStatus }
    CompositeTypes: {}
  }
}

export type Tables<T extends keyof (Database['public']['Tables'] & Database['public']['Views'])> = (Database['public']['Tables'] & Database['public']['Views'])[T] extends { Row: infer R } ? R : never
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
