import Link from 'next/link'
import { AlertTriangle, ClipboardList, FileText, GraduationCap, ListChecks } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { DashboardOverview, dashboardMetricIcons } from '@/components/dashboard/dashboard-overview'
import { KpiHeroCard } from '@/components/dashboard/kpi-hero-card'
import type { Database } from '@/types/database'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
export const dynamic='force-dynamic'
type ActionRow=Database['public']['Views']['vw_action_required']['Row']
export default async function Dashboard(){ const supabase=await createClient(); const {data:userData,error:userError}=await supabase.auth.getUser(); if(userError||!userData.user) return <div className="p-6"><Card className="mx-auto max-w-xl"><CardHeader><CardTitle>Session diperlukan</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-slate-500">Sila log masuk untuk melihat dashboard.</p><Button asChild><Link href="/login">Log masuk</Link></Button></CardContent></Card></div>; const [p,i,a,s,rows,overdue]=await Promise.all([supabase.from('programs').select('*',{count:'exact',head:true}),supabase.from('invoices').select('*',{count:'exact',head:true}),supabase.from('vw_action_required').select('*',{count:'exact',head:true}),supabase.from('training_sessions').select('*',{count:'exact',head:true}),supabase.from('vw_action_required').select('*').order('days_outstanding',{ascending:false}).limit(10),supabase.from('vw_action_required').select('amount').eq('category','OVERDUE_INVOICE')]); const actionRows=(rows.data??[]) as ActionRow[]; const overdueAmount=(overdue.data??[]).reduce((sum,r)=>sum+Number(r.amount??0),0); const high=actionRows.filter(r=>r.priority?.toUpperCase()==='HIGH').length; const metrics=[{label:'Programs',value:p.count??0,icon:ClipboardList,href:'/dashboard/programs',variant:'blue' as const},{label:'Invoices',value:i.count??0,icon:FileText,href:'/dashboard/r1',variant:'violet' as const},{label:'Action Items',value:a.count??0,icon:ListChecks,href:'/dashboard/action-center',variant:'amber' as const},{label:'Training Sessions',value:s.count??0,icon:GraduationCap,href:'/dashboard/r2',variant:'emerald' as const}]; return <div className="space-y-6 p-4 md:p-6"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Operations</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Dashboard</h1><p className="mt-1 text-sm text-slate-500">Ringkasan operasi program daripada Supabase.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><KpiHeroCard key={m.label} {...m}/>)}</div><div className="grid gap-4 md:grid-cols-2"><KpiHeroCard label="Total Overdue" value={`RM ${overdueAmount.toLocaleString('en-MY',{minimumFractionDigits:2})}`} icon={AlertTriangle} variant="rose"/><KpiHeroCard label="High-Priority Alerts" value={high} icon={AlertTriangle} variant="amber" href="/dashboard/action-center"/></div><DashboardOverview metrics={metrics.map(m=>({...m,tone:''}))} actions={actionRows} overdueAmount={overdueAmount}/></div> }
