import { createClient } from '@/lib/supabase/server'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { StatusBadge, type StatusType } from '@/components/ui/status-badge'
import type { Database } from '@/types/database'

export const dynamic = 'force-dynamic'
type R2Row = Database['public']['Views']['vw_r2_overall_report']['Row']
const r2Status = (status: string | null): StatusType => status?.toUpperCase() === 'COMPLETED' ? 'COMPLETED' : status?.toUpperCase() === 'PENDING_DATA' ? 'PENDING_DATA' : 'PENDING'

export default async function R2Page() {
  const supabase = await createClient()
  const { data, error } = await supabase.from('vw_r2_overall_report').select('*').order('start_date', { ascending: false })
  if (error) return <div className="space-y-6 p-6"><h1 className="text-2xl font-bold tracking-tight">R2 — Overall Report</h1><Card><CardContent className="p-6"><p className="text-sm text-slate-600">Data R2 tidak dapat dimuatkan sekarang.</p><p className="mt-2 text-xs text-red-600">{error.message}</p></CardContent></Card></div>
  const rows: R2Row[] = data ?? []
  const sessions = new Set(rows.map(r => r.program_code ?? '').filter(Boolean)).size
  const totalParticipants = rows.reduce((s, r) => s + Number(r.total_count ?? 0), 0)
  const totalBumi = rows.reduce((s, r) => s + Number(r.bumiputera_count ?? 0), 0)
  const totalNonBumi = rows.reduce((s, r) => s + Number(r.non_bumiputera_count ?? 0), 0)
  const [{ data: rosterRows, error: rosterError }, { data: sessionRows, error: sessionError }, { data: programRows, error: programError }] = await Promise.all([supabase.from('participant_roster').select('*').order('full_name', { ascending: true }).limit(500), supabase.from('training_sessions').select('*'), supabase.from('programs').select('id, program_code, title, needs_review')])
  const sessionById = new Map((sessionRows ?? []).map(r => [r.id, r])); const programById = new Map((programRows ?? []).map(r => [r.id, r]))
  const roster = (rosterRows ?? []).map(r => { const session = r.training_session_id ? sessionById.get(r.training_session_id) : undefined; const program = session ? programById.get(session.program_id) : undefined; return { ...r, session, program } })
  const certified = roster.filter(r => r.participation_type === 'CERTIFIED'), attended = roster.filter(r => r.participation_type === 'ATTENDED')
  const rosterSessions = new Set(roster.map(r => r.training_session_id).filter(Boolean)).size
  const needsReview = roster.filter(r => r.session?.r2_status === 'PENDING_DATA' || r.program?.needs_review)
  const hasRosterLoadError = Boolean(rosterError || sessionError || programError)
  return <div className="space-y-6 p-6">
    <div><h1 className="text-2xl font-bold tracking-tight">R2 — Overall Report</h1><p className="mt-1 text-sm text-slate-500">Dijana daripada training_sessions + participant_counts (view `vw_r2_overall_report`); roster dipaparkan daripada participant_roster.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Sessions',sessions],['Categories Rows',rows.length],['Certified Roster',certified.length],['Attendance Rows',attended.length],['Roster Sessions',rosterSessions]].map(([label,value]) => <Card key={String(label)}><CardContent className="p-5"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-[32px] font-semibold leading-[1.2] tabular-nums">{value}</p></CardContent></Card>)}</div>
    <Card><CardContent className="p-4 sm:p-6"><div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[1000px] text-[13px] leading-[1.4]"><thead className="sticky top-0 z-10 bg-slate-50 text-[11px] font-semibold uppercase tracking-wide text-slate-500"><tr>{['Program','Session','Company','Type','Start','End','Category','Workshop','Training','Total','Bumi','Non-Bumi','Status'].map((h,i)=><th key={h} className={`border-b border-slate-200 p-3 ${i>=7&&i<=11?'text-right':'text-left'}`}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.program_code}-${r.session_title}-${r.category}-${i}`} className="border-t border-slate-100 odd:bg-white even:bg-slate-50/50 hover:bg-slate-100/70"><td className="p-3 font-medium text-blue-600">{r.program_code??'—'}</td><td className="max-w-[300px] truncate p-3">{r.session_title??'—'}</td><td className="max-w-[220px] truncate p-3">{r.company_name??'—'}</td><td className="p-3">{r.session_type??'—'}</td><td className="p-3">{r.start_date?new Date(r.start_date).toLocaleDateString('en-MY'):'—'}</td><td className="p-3">{r.end_date?new Date(r.end_date).toLocaleDateString('en-MY'):'—'}</td><td className="p-3"><Badge>{r.category??'—'}</Badge></td><td className="p-3 text-right tabular-nums">{r.workshop_count??0}</td><td className="p-3 text-right tabular-nums">{r.training_count??0}</td><td className="p-3 text-right tabular-nums">{r.total_count??0}</td><td className="p-3 text-right tabular-nums">{r.bumiputera_count??0}</td><td className="p-3 text-right tabular-nums">{r.non_bumiputera_count??0}</td><td className="p-3"><StatusBadge status={r2Status(r.r2_status)} label={r.r2_status??'PENDING'} /></td></tr>)}</tbody></table></div>{rows.length===0?<p className="py-10 text-center text-sm text-slate-500">Tiada data R2. Import R2 Overall Report untuk melihat laporan.</p>:null}<p className="mt-3 text-xs text-slate-500">Total peserta kategori: {totalParticipants} · Bumiputera: {totalBumi} · Non-Bumiputera: {totalNonBumi}</p></CardContent></Card>
    <Card><CardContent className="p-4 sm:p-6"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Participant Roster &amp; Attendance</h2><p className="mt-1 text-xs text-slate-500">Dari sheet Attendance list melalui `commit_r2_roster()`. Baris attendance direkodkan per minggu (Week 1 / Week 2).</p></div>{hasRosterLoadError?<StatusBadge status="PENDING_DATA" label="Data roster tidak lengkap"/>:null}</div>{needsReview.length>0?<p className="mb-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700">{needsReview.length} baris tergolong dalam sesi attendance tanpa padanan exact dalam Overall report; ia telah dicipta sebagai sesi standalone dan masih perlu disemak.</p>:null}<div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[1000px] text-[13px] leading-[1.4]"><thead className="sticky top-0 z-10 bg-slate-50 text-[11px] font-semibold uppercase tracking-wide text-slate-500"><tr>{['Program','Session','Name','Cert No','Type','Week','Bumi','Review','Source Row'].map((h,i)=><th key={h} className={`border-b border-slate-200 p-3 ${i===8?'text-right':'text-left'}`}>{h}</th>)}</tr></thead><tbody>{roster.map(r=>{const review=r.session?.r2_status==='PENDING_DATA'||r.program?.needs_review; return <tr key={r.id} className="border-t border-slate-100 odd:bg-white even:bg-slate-50/50 hover:bg-slate-100/70"><td className="p-3 font-medium text-blue-600">{r.program?.program_code??'—'}</td><td className="max-w-[280px] truncate p-3">{r.session?.session_title??'—'}</td><td className="max-w-[240px] truncate p-3">{r.full_name}</td><td className="p-3 text-xs">{r.cert_no??'—'}</td><td className="p-3"><StatusBadge status={r.participation_type==='CERTIFIED'?'COMPLETED':'PARTIAL'} label={r.participation_type}/></td><td className="p-3">{r.week_label??'—'}</td><td className="p-3">{r.is_bumiputera==null?'—':r.is_bumiputera?'Bumi':'Non-Bumi'}</td><td className="p-3">{review?<StatusBadge status="PENDING_DATA" label="Review"/>:'—'}</td><td className="p-3 text-right tabular-nums">{r.source_row??'—'}</td></tr>})}</tbody></table></div>{roster.length===0?<p className="py-10 text-center text-sm text-slate-500">Tiada participant roster. Import &amp; commit R2 untuk mengisi jadual ini.</p>:null}{roster.length>0?<p className="mt-3 text-xs text-slate-500">{certified.length} certified · {attended.length} attendance records · {needsReview.length} perlu review. Menunjukkan sehingga 500 baris.</p>:null}</CardContent></Card>
  </div>
}
