create extension if not exists pgcrypto;
create type user_role as enum ('super_admin','admin','manager','pic','viewer');
create type pipeline_stage as enum ('LEAD_REGISTERED','PROPOSAL_SUBMITTED','QUOTATION_APPROVED','PO_RECEIVED','INVOICED','PAID','TRAINING_COMPLETED','LOST');
create type quotation_status as enum ('DRAFT','SENT','PENDING','APPROVED','REJECTED','EXPIRED');
create type payment_status as enum ('UNPAID','PARTIAL','PAID','OVERDUE');
create type training_type as enum ('PUBLIC','IN_HOUSE','CERT_PRINTING','SPACE_RENTAL');
create type r2_status as enum ('COMPLETED','PENDING_DATA','UPCOMING');
create type exception_status as enum ('OPEN','RESOLVED','IGNORED');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text not null, email text not null unique, role user_role not null default 'viewer', pic_display_name text, is_active boolean not null default true, must_reset_password boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.companies(id uuid primary key default gen_random_uuid(), canonical_name text not null, aliases text[] not null default '{}', client_category text, sector text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.programs(id uuid primary key default gen_random_uuid(), program_code text not null unique, title text not null, company_id uuid not null references public.companies(id), category text, training_type training_type, current_stage pipeline_stage not null default 'LEAD_REGISTERED', client_category text, sector text, pic_user_id uuid references public.profiles(id), account_manager_user_id uuid references public.profiles(id), lead_date date, forecast_value numeric(14,2), probability numeric(4,3) check(probability between 0 and 1), needs_review boolean not null default false, source_file text, source_sheet text, source_row int, row_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.programs add column weighted_value numeric(14,2) generated always as (round(coalesce(forecast_value,0)*coalesce(probability,0),2)) stored;
create table public.pipeline_stage_history(id uuid primary key default gen_random_uuid(), program_id uuid not null references public.programs(id) on delete cascade, stage pipeline_stage not null, changed_at timestamptz not null default now(), changed_by uuid references public.profiles(id), note text, is_override boolean not null default false, override_reason text, source_system text);
create table public.quotations(id uuid primary key default gen_random_uuid(), program_id uuid not null references public.programs(id) on delete cascade, quotation_no_raw text not null, quotation_series text, quotation_year int, quotation_seq int, revision_no int not null default 0, quotation_date date, final_price numeric(14,2), status quotation_status not null default 'DRAFT', prepared_by text, source_file text, source_sheet text, source_row int, row_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(quotation_no_raw,revision_no,source_file));
create table public.purchase_orders(id uuid primary key default gen_random_uuid(), program_id uuid not null references public.programs(id) on delete cascade, quotation_id uuid references public.quotations(id), po_no text, po_date date, po_value numeric(14,2), source_file text, source_sheet text, source_row int, row_hash text, created_at timestamptz not null default now());
create table public.invoices(id uuid primary key default gen_random_uuid(), program_id uuid not null references public.programs(id) on delete cascade, quotation_id uuid references public.quotations(id), po_id uuid references public.purchase_orders(id), invoice_no text not null, invoice_date date, invoice_value_excl_sst numeric(14,2) not null default 0, sst_amount numeric(14,2) not null default 0, payment_terms_days int not null default 30, payment_status payment_status not null default 'UNPAID', payment_method text, account text, account_manager text, pic text, remark text, source_file text, source_sheet text, source_row int, row_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(invoice_no,source_file));
create view public.vw_invoices as select i.*, i.invoice_value_excl_sst+i.sst_amount as total_value, case when i.invoice_date is null then null else i.invoice_date+i.payment_terms_days end as due_date, case when i.payment_status='PAID' or i.invoice_date is null then 0 else greatest(0,current_date-(i.invoice_date+i.payment_terms_days)) end as days_outstanding from public.invoices i;
create table public.payments(id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, amount numeric(14,2) not null check(amount>0), payment_date date not null default current_date, method text, reference_no text, recorded_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.training_sessions(id uuid primary key default gen_random_uuid(), program_id uuid not null references public.programs(id) on delete cascade, session_title text not null, session_type training_type, start_date date, end_date date, venue text, duration_days numeric(6,2), r2_status r2_status not null default 'UPCOMING', source_file text, source_sheet text, source_row int, row_hash text, created_at timestamptz not null default now());
create table public.participant_counts(id uuid primary key default gen_random_uuid(), training_session_id uuid not null references public.training_sessions(id) on delete cascade, category text not null default 'OTHERS', bumiputera_count int not null default 0, non_bumiputera_count int not null default 0, unique(training_session_id,category));
create table public.data_quality_exceptions(id uuid primary key default gen_random_uuid(), type text not null, severity text not null default 'MED', description text not null, related_table text, related_id uuid, status exception_status not null default 'OPEN', resolved_by uuid references public.profiles(id), resolved_at timestamptz, resolution_note text, created_at timestamptz not null default now());
create table public.import_batches(id uuid primary key default gen_random_uuid(), file_name text not null, storage_path text not null, uploaded_by uuid references public.profiles(id), status text not null default 'uploaded', total_rows int not null default 0, new_records int not null default 0, updated_records int not null default 0, rejected_rows int not null default 0, error_summary jsonb, created_at timestamptz not null default now(), committed_at timestamptz);
create table public.audit_log(id uuid primary key default gen_random_uuid(), table_name text not null, record_id uuid not null, action text not null, old_value jsonb, new_value jsonb, changed_by uuid references public.profiles(id), changed_at timestamptz not null default now(), source text default 'app');

create view public.vw_r1_income_statement as select p.program_code,c.canonical_name company_name,p.title,i.invoice_no,i.invoice_date,i.invoice_value_excl_sst,i.sst_amount,i.invoice_value_excl_sst+i.sst_amount total_value,i.payment_status,(case when i.invoice_date is null then null else i.invoice_date+i.payment_terms_days end) due_date,(case when i.payment_status='PAID' or i.invoice_date is null then 0 else greatest(0,current_date-(i.invoice_date+i.payment_terms_days)) end) days_outstanding,i.account,i.pic from public.invoices i join public.programs p on p.id=i.program_id join public.companies c on c.id=p.company_id;
create view public.vw_r2_overall_report as select p.program_code,c.canonical_name company_name,ts.session_title,ts.session_type,ts.start_date,ts.end_date,ts.r2_status,pc.category,pc.bumiputera_count,pc.non_bumiputera_count,(pc.bumiputera_count+pc.non_bumiputera_count) total_count from public.training_sessions ts join public.programs p on p.id=ts.program_id join public.companies c on c.id=p.company_id left join public.participant_counts pc on pc.training_session_id=ts.id;
create view public.vw_r3_sales_funnel as select p.program_code,c.canonical_name company_name,p.title,p.current_stage,p.forecast_value,p.probability,p.weighted_value,p.pic_user_id,p.sector,p.lead_date from public.programs p join public.companies c on c.id=p.company_id where p.current_stage <> 'LOST';
create view public.vw_action_required as select 'OVERDUE_INVOICE' category,i.id record_id,p.program_code,c.canonical_name company_name,(i.invoice_value_excl_sst+i.sst_amount) amount,greatest(0,current_date-(i.invoice_date+i.payment_terms_days)) days_outstanding,i.pic,'HIGH' priority from public.invoices i join public.programs p on p.id=i.program_id join public.companies c on c.id=p.company_id where i.payment_status<>'PAID' and i.invoice_date is not null and current_date>(i.invoice_date+i.payment_terms_days+30) union all select 'PENDING_QUOTATION',q.id,p.program_code,c.canonical_name,q.final_price,current_date-q.quotation_date,q.prepared_by,'MED' from public.quotations q join public.programs p on p.id=q.program_id join public.companies c on c.id=p.company_id where q.status in('SENT','PENDING') and q.quotation_date is not null and current_date-q.quotation_date>14 union all select 'DATA_EXCEPTION',d.id,null,null,null,null,null,d.severity from public.data_quality_exceptions d where d.status='OPEN';

create or replace function public.audit_row() returns trigger language plpgsql security invoker as $$ begin insert into public.audit_log(table_name,record_id,action,old_value,new_value,changed_by) values(TG_TABLE_NAME,coalesce(new.id,old.id),TG_OP,to_jsonb(old),to_jsonb(new),auth.uid()); return coalesce(new,old); end $$;

do $$ declare t text; begin foreach t in array array['programs','quotations','purchase_orders','invoices','payments','training_sessions','companies'] loop execute format('create trigger audit_%s after insert or update or delete on public.%s for each row execute function public.audit_row()',t,t); end loop; end $$;

alter table public.profiles enable row level security; alter table public.companies enable row level security; alter table public.programs enable row level security; alter table public.pipeline_stage_history enable row level security; alter table public.quotations enable row level security; alter table public.purchase_orders enable row level security; alter table public.invoices enable row level security; alter table public.payments enable row level security; alter table public.training_sessions enable row level security; alter table public.participant_counts enable row level security; alter table public.data_quality_exceptions enable row level security; alter table public.import_batches enable row level security; alter table public.audit_log enable row level security;
create or replace function public.has_role(required_roles text[]) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active and p.role::text=any(required_roles)); $$;
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or public.has_role(array['super_admin','admin','manager']));
create policy companies_read on public.companies for select to authenticated using(true); create policy companies_write on public.companies for all to authenticated using(public.has_role(array['super_admin','admin'])) with check(public.has_role(array['super_admin','admin']));
create policy programs_read on public.programs for select to authenticated using(true); create policy programs_insert on public.programs for insert to authenticated with check(public.has_role(array['super_admin','admin','manager','pic'])); create policy programs_update on public.programs for update to authenticated using(public.has_role(array['super_admin','admin','manager']) or pic_user_id=auth.uid()) with check(public.has_role(array['super_admin','admin','manager']) or pic_user_id=auth.uid());
create policy stage_read on public.pipeline_stage_history for select to authenticated using(true); create policy stage_write on public.pipeline_stage_history for insert to authenticated with check(public.has_role(array['super_admin','admin','manager','pic']));
create policy quotation_read on public.quotations for select to authenticated using(true); create policy quotation_write on public.quotations for all to authenticated using(public.has_role(array['super_admin','admin','manager','pic'])) with check(public.has_role(array['super_admin','admin','manager','pic']));
create policy po_read on public.purchase_orders for select to authenticated using(true); create policy po_write on public.purchase_orders for all to authenticated using(public.has_role(array['super_admin','admin','manager','pic'])) with check(public.has_role(array['super_admin','admin','manager','pic']));
create policy invoice_read on public.invoices for select to authenticated using(true); create policy invoice_write on public.invoices for all to authenticated using(public.has_role(array['super_admin','admin'])) with check(public.has_role(array['super_admin','admin']));
create policy payment_read on public.payments for select to authenticated using(true); create policy payment_insert on public.payments for insert to authenticated with check(public.has_role(array['super_admin','admin','manager','pic'])); create policy payment_update on public.payments for update to authenticated using(public.has_role(array['super_admin','admin']));
create policy training_read on public.training_sessions for select to authenticated using(true); create policy training_write on public.training_sessions for all to authenticated using(public.has_role(array['super_admin','admin','manager','pic'])) with check(public.has_role(array['super_admin','admin','manager','pic']));
create policy participant_read on public.participant_counts for select to authenticated using(true); create policy participant_write on public.participant_counts for all to authenticated using(public.has_role(array['super_admin','admin','manager','pic'])) with check(public.has_role(array['super_admin','admin','manager','pic']));
create policy exception_read on public.data_quality_exceptions for select to authenticated using(true); create policy exception_write on public.data_quality_exceptions for all to authenticated using(public.has_role(array['super_admin','admin','manager'])) with check(public.has_role(array['super_admin','admin','manager']));
create policy import_write on public.import_batches for all to authenticated using(public.has_role(array['super_admin','admin','pic'])) with check(public.has_role(array['super_admin','admin','pic']));
create policy audit_read on public.audit_log for select to authenticated using(public.has_role(array['super_admin','admin','manager']));

-- Supabase Data API exposure is explicit for current/new projects.
grant select on public.vw_r1_income_statement,public.vw_r2_overall_report,public.vw_r3_sales_funnel,public.vw_action_required to authenticated;
grant select on public.profiles,public.companies,public.programs,public.quotations,public.purchase_orders,public.invoices,public.payments,public.training_sessions,public.participant_counts,public.data_quality_exceptions to authenticated;
grant insert,update,delete on public.companies,public.programs,public.quotations,public.purchase_orders,public.payments,public.training_sessions,public.participant_counts,public.data_quality_exceptions,public.import_batches to authenticated;
grant insert,update,delete on public.invoices to authenticated;
