create extension if not exists pgcrypto;
create type user_role as enum ('super_admin','admin','manager','pic','viewer');
create type pipeline_stage as enum ('LEAD_REGISTERED','PROPOSAL_SUBMITTED','QUOTATION_APPROVED','PO_RECEIVED','INVOICED','PAID','TRAINING_COMPLETED','LOST');
create type quotation_status as enum ('DRAFT','SENT','PENDING','APPROVED','REJECTED','EXPIRED');
create type payment_status as enum ('UNPAID','PARTIAL','PAID','OVERDUE');
create type r2_status as enum ('COMPLETED','PENDING_DATA','UPCOMING');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,email text not null unique,role user_role not null default 'viewer',is_active boolean not null default true,must_reset_password boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.companies(id uuid primary key default gen_random_uuid(),canonical_name text not null,aliases text[] not null default '{}',client_category text,sector text,is_merged_into uuid references public.companies(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.programs(id uuid primary key default gen_random_uuid(),program_code text not null unique,title text not null,company_id uuid not null references public.companies(id),category text,training_type text,current_stage pipeline_stage not null default 'LEAD_REGISTERED',client_category text,sector text,pic_user_id uuid references public.profiles(id),account_manager_user_id uuid references public.profiles(id),lead_date date,forecast_value numeric(14,2),probability numeric(4,3),weighted_value numeric(14,2) generated always as (round(coalesce(forecast_value,0)*coalesce(probability,0),2)) stored,needs_review boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.pipeline_stage_history(id uuid primary key default gen_random_uuid(),program_id uuid not null references public.programs(id) on delete cascade,stage pipeline_stage not null,changed_at timestamptz not null default now(),changed_by uuid references public.profiles(id),note text,is_override boolean not null default false,override_reason text,source_system text);
create table public.quotations(id uuid primary key default gen_random_uuid(),program_id uuid not null references public.programs(id) on delete cascade,quotation_no_raw text not null,quotation_date date,final_price numeric(14,2),status quotation_status not null default 'DRAFT',prepared_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(quotation_no_raw,program_id));
create table public.purchase_orders(id uuid primary key default gen_random_uuid(),program_id uuid not null references public.programs(id) on delete cascade,quotation_id uuid references public.quotations(id),po_no text,po_date date,po_value numeric(14,2),created_at timestamptz not null default now());
create table public.invoices(id uuid primary key default gen_random_uuid(),program_id uuid not null references public.programs(id) on delete cascade,quotation_id uuid references public.quotations(id),po_id uuid references public.purchase_orders(id),invoice_no text not null,invoice_date date,invoice_value_excl_sst numeric(14,2) not null default 0,sst_amount numeric(14,2) not null default 0,total_value numeric(14,2) generated always as (invoice_value_excl_sst+sst_amount) stored,payment_terms_days int not null default 30,due_date date generated always as (invoice_date+make_interval(days=>payment_terms_days)) stored,payment_status payment_status not null default 'UNPAID',pic text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(invoice_no,program_id));
create table public.payments(id uuid primary key default gen_random_uuid(),invoice_id uuid not null references public.invoices(id) on delete cascade,amount numeric(14,2) not null check(amount>0),payment_date date not null default current_date,method text,reference_no text,recorded_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.training_sessions(id uuid primary key default gen_random_uuid(),program_id uuid not null references public.programs(id) on delete cascade,session_title text not null,session_type text,start_date date,end_date date,venue text,duration_days numeric(6,2),r2_status r2_status not null default 'UPCOMING',created_at timestamptz not null default now());
create table public.data_quality_exceptions(id uuid primary key default gen_random_uuid(),type text not null,severity text not null default 'MED',description text not null,related_table text,related_id uuid,status text not null default 'OPEN',resolved_by uuid references public.profiles(id),resolved_at timestamptz,resolution_note text,created_at timestamptz not null default now());
create table public.audit_log(id uuid primary key default gen_random_uuid(),table_name text not null,record_id uuid not null,action text not null,old_value jsonb,new_value jsonb,changed_by uuid references public.profiles(id),changed_at timestamptz not null default now(),source text not null default 'app');

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),new.email) on conflict(id) do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace view public.vw_r3_sales_funnel with (security_invoker=true) as select p.program_code,c.canonical_name company_name,p.title,p.current_stage,p.forecast_value,p.probability,p.weighted_value,p.pic_user_id,p.sector,p.lead_date,coalesce((select sum(po.po_value) from public.purchase_orders po where po.program_id=p.id),0) secured_value from public.programs p join public.companies c on c.id=p.company_id where p.current_stage<>'LOST';
create or replace view public.vw_action_required with (security_invoker=true) as select 'OVERDUE_INVOICE' category,i.id record_id,p.program_code,c.canonical_name company_name,i.total_value amount,greatest(0,current_date-i.due_date) days_outstanding,i.pic,'HIGH' priority from public.invoices i join public.programs p on p.id=i.program_id join public.companies c on c.id=p.company_id where i.payment_status<>'PAID' and i.due_date<current_date union all select 'PENDING_QUOTATION',q.id,p.program_code,c.canonical_name,q.final_price,greatest(0,current_date-q.quotation_date),q.prepared_by,case when current_date-q.quotation_date>30 then 'HIGH' else 'MED' end from public.quotations q join public.programs p on p.id=q.program_id join public.companies c on c.id=p.company_id where q.status in('SENT','PENDING') and q.quotation_date<current_date-14 union all select 'INCOMPLETE_R2',ts.id,p.program_code,c.canonical_name,null,greatest(0,current_date-ts.end_date),null,'MED' from public.training_sessions ts join public.programs p on p.id=ts.program_id join public.companies c on c.id=p.company_id where ts.r2_status='PENDING_DATA' and ts.end_date<current_date union all select 'DATA_EXCEPTION',d.id,null,null,null,null,null,d.severity from public.data_quality_exceptions d where d.status='OPEN';

alter table public.profiles enable row level security;alter table public.companies enable row level security;alter table public.programs enable row level security;alter table public.pipeline_stage_history enable row level security;alter table public.quotations enable row level security;alter table public.purchase_orders enable row level security;alter table public.invoices enable row level security;alter table public.payments enable row level security;alter table public.training_sessions enable row level security;alter table public.data_quality_exceptions enable row level security;alter table public.audit_log enable row level security;
create policy profiles_self on public.profiles for select to authenticated using(id=auth.uid());
create policy companies_read on public.companies for select to authenticated using(true);create policy companies_write on public.companies for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin'))) with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin')));
create policy programs_read on public.programs for select to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','viewer')) or pic_user_id=auth.uid() or account_manager_user_id=auth.uid());create policy programs_write on public.programs for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')) or pic_user_id=auth.uid()) with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')) or pic_user_id=auth.uid());
create policy chain_read on public.pipeline_stage_history for select to authenticated using(true);create policy chain_write on public.pipeline_stage_history for insert to authenticated with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')));
create policy quotation_read on public.quotations for select to authenticated using(true);create policy quotation_write on public.quotations for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')));
create policy po_read on public.purchase_orders for select to authenticated using(true);create policy po_write on public.purchase_orders for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')));
create policy invoice_read on public.invoices for select to authenticated using(true);create policy invoice_write on public.invoices for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')));
create policy payment_read on public.payments for select to authenticated using(true);create policy payment_write on public.payments for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')));
create policy training_read on public.training_sessions for select to authenticated using(true);create policy training_write on public.training_sessions for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')));
create policy dqe_read on public.data_quality_exceptions for select to authenticated using(true);create policy dqe_write on public.data_quality_exceptions for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin','manager','pic')));
create policy audit_read on public.audit_log for select to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in('super_admin','admin')));
